### ISSUE TITLE
Port Totem Huginn to Ruby

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#14]
Totem - All events are on the same web page: https://totemcontemporain.com/fr/calendrier

Old Huginn: https://huginn-staging.herokuapp.com/scenarios/25

Please call this artifact: totemcontemporain-com

**Comment by dev-aravind** [comment]
@saumier I updated the code to fetch the [data](https://raw.githubusercontent.com/culturecreates/artsdata-orion/main/output/totem-events.jsonld), the jsonld has people and places in it, but it is not appearing in Nebula. Can you check on this?

I think this is happening because the type of the data mentioned is http://schema.org/person, not http://schema.org/Person

**Comment by saumier** [comment]
@dev-aravind Please write a sparql that will change `http://schema.org/person` into `http://schema.org/Person`.  Later on we may decide to move this sparql into the Artsdata Databus to fix this for everyone since this is probably a common mistake.

**Comment by dev-aravind** [comment]
@saumier Please look into this [PR](https://github.com/culturecreates/artsdata-orion/pull/25) I've added the SPARQL as well as unit tests to fix the type object.

**Comment by saumier** [comment]
@dev-aravind This issue is related to the same PR for which I requested some changes, so I will leave this one in review until the PR is closed.
