### ISSUE TITLE
Port Capitol Theatre Huginn to Ruby

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#17]
Capitol theatre located in the city of Nelson in the province of British Columbia

 https://capitoltheatre.ca - try to find webpages with structured data for events 

Watch out for place with same name but in another Canadian city.

Old Huginn: https://huginn-staging.herokuapp.com/scenarios/7

Please name this artifact: capitoltheatre-ca

**Comment by dev-aravind** [comment]
@saumier I wrote a workflow for this website and the data is up in [artsdata](https://artsdata-nebula-d1ec887e2637.herokuapp.com/query/show?title=Event%20entities%20in%20capitoltheatre-ca%20%2819952%20triples%29&sparql=list_events&placeholder=http://kg.artsdata.ca/culture-creates/artsdata-orion/capitoltheatre-ca). However, there is a SHACL violation for te events because the Performer is set as "Organizer for some reason". Also, there are a lot of duplicated data in the events. Let me know what you think.

**Comment by saumier** [comment]
@dev-aravind I don't see the "prov:wasDerivedFrom" triples that we must add when generating blank nodes.

**Comment by dev-aravind** [comment]
@saumier I've removed the duplicate URLs, but each event page has the JSON-LD details of other events in the "Buy tickets" section. 

please refer this: https://capitoltheatre.ca/event/snowed-in-comedy-tour-2024/

**Comment by saumier** [comment]
@dev-aravind I have taken a look. I see the problem with the "Buy tickets" section. I am still thinking about a way to handle this common mistake made on web sites in a generic way.

There are also more pages of events that we should be getting. Like this one https://capitoltheatre.ca/event/ballet-jorgen-anne-of-green-gables-capitol-season/

**Comment by dev-aravind** [comment]
@saumier I updated the workflow to fetch from another URL which covers more events. Please check it out and let me know if you have any questions.
